TimSort.java

Implementation of TimSort in java.

 TimSort.java

---

BinaryHeap.java

ADDED IMPLEMENTATION OF BINARY HEAP IN JAVA. HOPE THIS IS HELPFUL TO THE REPO.

Added Binary Heap

---

ToCheckTheGivenTwoStringsAreAnagramOrNot.java

This is a very good problem on interview question. I added optimized JAVA code for tha. please accept my PR with hacktoberfest-accepted label

ToCheckTheGivenTwoStringsAreAnagramOrNot.java

---

Two pointers searching.cpp

Implementation of Two pointers searching technique in cpp

 Two pointers searching.cpp

---

Identical Trees

Identical Tree implementation in java.

Identical Trees

---

Mirror Tree

Mirror Tree implementation in java.

Mirror Tree

---

comparison_game.java

I have made a simple comparison_game.java

comparison_game.java

---

Maximum Area Histogram.cpp

Solution to DSA Problem: Maximum area of a histogram

Create Maximum Area Histogram.cpp

---

array_program.cpp

created an array program to find the most frequent element in an array

created array program

---

PalindromePairUsingTries

2 Inputs are required-
1) No of words. \n
2) Actual Phrase/words.
Output-
The first and only line of output contains true if the conditions described in the task are met and false otherwise.

PalindromePairUsingTries

---

AVL Tree.cpp

AVL tree is a type of self balancing binary search tree. I have implemented all basic operations like insert, delete, etc for AVL tree.

Created AVL Tree.cpp

---

PatternMatching

Issue #47 resolved.
3 inputs are needed:
1) No. of words in the phrase in which you will be searching the pattern. \n 
2) Actual Phrase. \n
3) The Pattern you want to search.

PatternMatching

---

check_redundant_brackets.java
delete_every_n_nodes.java
minimum_bracket_reversal_stacks.java

1. Delete Every 'n' node in a LL
2. Check Redundant Brackets 
3. Minimum Bracket Reversal

Added 3 Programs

---

Nearest Smaller to Left.cpp

Nearest Smaller to Left code in C++

Create Nearest Smaller to Left.cpp

---

Prim's_algorithm.cpp

Standard algorithm to find minimum spanning tree in a graph

Added Prim's algorithm code

---

KadanesAlgorithm.py

Added Kadanes Algorithm in Python

added Kadanes Algorithm

---

ZerosAndOnesPattern.cpp

Suppose you give the size of row: 7
Output:
1
10
101
1010
10101
101010
1010101

Zeros and One's Pattern using C++

---

Number of Segments in a String.java
Power of Two.java

Number of Segments in a String and Power of Two.

Added 2 new problems from LeetCode in java

---

Count Negative Numbers in a Sorted Matrix.java

Create Count Negative Numbers in a Sorted Matrix.java file added

Added one problem from LeetCode in Java

---

Efficient_nCr.cpp

Added Efficient Algorithm for Finding nCr using Dynamic programming

Added Efficient nCr Code

---

Linklist.cpp

implementation of linked list with insertion and deletion operations

implementation of linked list in c++.

---

TicTacToe.py

Added TicTacToe Project made using python language

added tictactoe project

---

radixSort.cpp

Added Code for Radix Sort in C++ with Explanation

Added Radix Sort code in C++

---

BankManagementSysytem.py

Added Bank Management System 
The main objective of the project is to develop online Banking system for banks. There are many local banks where the banking work is still done manually. Users have to visit bank to Withdrawal or Deposit amount. In present bank system it is also difficult to find account information of account holder. In this bank management system we will automate all the banking process. In our bank management system user can check his balance online and he can also transfer money to other account online. In this code you can keep record for daily Banking transactions. The main aim of developing bank management system is to design an application, which could store bank  data and provide an interface for retrieving customer related details with 100% accuracy. This bank …

added bank management system

---

CardGame.py

A card game in python added. This generates random cards for two players. One with greater card wins the round.

A card game added

---

Reverse_Palindrome.java

Added a Reverse Palindrome Program created using Java language.

Added a Reverse Palindrome Program

---

N-ary Tree Level Order Traversal.java
search-in-rotated-sorted-array.java

1. N-ary Tree Level Order Traversal
2. Search in Rotated Sorted Array

Added 2 LeetCode Problems (in Java)

---

Spiral_Representation_Fibonacci_(Turtle).py

A data visualizer for the Fibonacci series in Python.

Adding a Spiral representation for the Fibonacci Series.

---

circularLinkList.cpp

Here,I'm added All basic Implementation Circular Linklist ,Easy to understand Everyone
* Construct the Node
* Insert at the Begining (Navie method)
* insert at the Begining (Efficient Method)
* Insert at the End (Navie)
* Insert at the End(Efficent Apporach)
* Delete Kth Element
* Display

Added code for Circular Linklist basic Implementation

---

java applet projects/Border_Demo.java
java applet projects/FillPolyDemo.java
java applet projects/KeyDemo.java
java applet projects/MouseDemo.java
java applet projects/RoundRect.java
java applet projects/calculator.java

Programs are:
1. Border layout
2. mini Calculator
3. Mouse Methods
4. Key Methods
5. Fill Polygon
6. Rounded Rectangle

java applet projects

---

Spiral_Matrix.py

It's a program of spiral traversing of a 2D array in python.

Spiral Traversing of a 2D Array.

---

Largest_Element_in _an_Array.java

This is a Java Program to Find the Largest Number in an Array.

Create Largest_Element_in _an_Array.java

---

Bellman–Ford Algorithm.java

The idea is to use the Bellman-Ford algorithm to compute the shortest paths from a single source vertex to all the other vertices in a given weighted digraph.

Create Bellman–Ford Algorithm.java

---

First Unique Character in a String
Number of 1 Bits.cpp

Create First Unique Character in a String.cpp

---

C++ Program to Swap Two Numbers

Create C++ Program to Swap Two Numbers

---

Boyer–Moore Majority Vote Algorithm.py

This is linear time solution using Hashing for Finding Major element using Boyer–Moore Majority Vote Algorithm

Create Boyer–Moore Majority Vote Algorithm.py

---

Password_Generator.py

Added a unique and strong Password Generator

---

determinant.cpp

please consider it for hacktoberfest 2022

added a new cpp file to compute the determinant of a matrix

---

spiral_array.java

spiral array

---

bucketsort.java
checkprime.java
heapsort.java

Hey ! I saw that there are many sorting algorithms  in this repo . I added Bucketsort .

created bucketsort

---

FibonacciGenerator.c

Kindly merge this pull request asap!! Thanks: )) !

C program in C language is added!!

---

Guessing Game.py

1. If a player's guess is less than 1 or greater than 100, say "OUT OF BOUNDS"
2. On a player's first turn, if their guess is
- within 10 of the number, return "WARM!"
- further than 10 away from the number, return "COLD!"
3. On all subsequent turns, if a guess is
- closer to the number than the previous guess return "WARMER!"
- farther from the number than the previous guess, return "COLDER!"
4. When the player's guess equals the number, tell them they've guessed correctly and how many guesses it took!

Guessing Game Added

---

Longest Palindromic Substring.cpp

Leetcode Problem: 5. Longest Palindromic Substring

Create Longest Palindromic Substring.cpp

---

SlidingWindowMaximum.cpp
primsAlgoMST.cpp

I have added sliding window maximum problem

sliding window maximum problem

---

BrickBallGame.js

Added the js Backend of the classical Brick Ball Game

Added Brick Ball Game

---

kruskal.cpp

Description: Added my own code for kruskal's algorithm for hacktoberfest

Title: Add kruskal's Algorithm

---

half_pyramid_pattern.java

added a java program

---

bArraySearch.cpp

feat: added binary array search for hacktoberfest

---

bubbleSort.cpp

feat: added bubble sort in C++ for hacktoberfest

---

LinkedList.py

Adding Linked List code in Python.

Adding Linked List in Python

---

c.py

This is the tcp client code written in python

TCP client in python

---

Calculator.html

I have added a html, css, js code for a webpage of a Simple Calculator which can perform following functions:
1) Addition
2) Subtraction
3) Multiplication
4) Division
5) Modulo

Adding the html code for Calculator

---

LinkedList.java

Adding program for Linked List Java

Adding LinkedList in Java

---

GroupAnagrams.cpp

Group anagrams together from a list of words in cpp

added groupAnagrams

---

BMI Calculator/index.html
BMI Calculator/index.js
BMI Calculator/style.css

I have added a simple BMI calculator made using HTML, CSS and JavaScript

My First Commit

---

SelectionSort.java

Added a Selection Sort program in Java.

Selection Sort Technique

---

TravelingSalesman.java

Adding program to execute Traveling Salesman Algorithm

Adding Traveling Salesman Code

---

Armstrong.java

Adding program to find if a number is Armstrong or not in Java.

Adding Armstrong Code in Java

---

Table Tennis scorekeeper/README.md
Table Tennis scorekeeper/app.js
Table Tennis scorekeeper/bank.cpp
Table Tennis scorekeeper/index.html

Hey there, I have added Table Tennis Scorekeeper(Basic Web Development Project).Please accept my pull request.

Table Tennis Scorekeeper added
